---
# control
control:
  num_users: '8'
  assist_mode: 'stack'
  local_epoch: '10'
  global_epoch: '10'
  assist_rate_mode: 'search'
  noise: '0'
  al: '0'
  rl: 'none'
  dl: '1'
  pl: 'none'
# data
data_name: CIFAR10
# MNIST
model_name: conv
# experiment
pin_memory: False
num_workers: 0
init_seed: 0
num_experiments: 1
log_interval: 0.25
device: cuda
world_size: 1
resume_mode: 0
